//types for user action 
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';

export const SUBMIT_RENTAL_REQUEST = 'SUBMIT_RENTAL_REQUEST';
export const SUBMIT_RENTAL_SUCCESS = 'SUBMIT_RENTAL_SUCCESS';
export const SUBMIT_RENTAL_FAILURE = 'SUBMIT_RENTAL_FAILURE';

//types for book action 
export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';

export const RENTER_FETCH_BOOKS_REQUEST = 'RENTER_FETCH_BOOKS_REQUEST';
export const OWNER_FETCH_BOOKS_REQUEST = 'OWNER_FETCH_BOOKS_REQUEST';
export const ADMIN_FETCH_BOOKS_REQUEST = 'ADMIN_FETCH_BOOKS_REQUEST';

export const ACCEPT_BOOK = 'ACCEPT_BOOK';
export const REJECT_BOOK = 'REJECT_BOOK';

export const SET_SEARCH_BOOK = 'SET_SEARCH_BOOK';


export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';

export const FETCH_RENTS_REQUEST = 'FETCH_RENTS_REQUEST';
export const FETCH_RENTS_SUCCESS = 'FETCH_RENTS_SUCCESS';
export const FETCH_RENTS_FAILURE = 'FETCH_RENTS_FAILURE';
export const ACCEPT_RENT_REQUEST = 'ACCEPT_RENT_REQUEST';
export const ACCEPT_RENT_SUCCESS = 'ACCEPT_RENT_SUCCESS';
export const ACCEPT_RENT_FAILURE = 'ACCEPT_RENT_FAILURE';
export const REJECT_RENT_REQUEST = 'REJECT_RENT_REQUEST';
export const REJECT_RENT_SUCCESS = 'REJECT_RENT_SUCCESS';
export const REJECT_RENT_FAILURE = 'REJECT_RENT_FAILURE';